baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tilemoon Blog'
theme = 'Marin'

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]

[menu]
  [[menu.main]]
    identifier = "homepage"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 2

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile"
    weight = 3
