baseURL = 'https://tilemoon.life/'
languageCode = 'en-us'
title = 'Tilemoon Blog'
theme = 'marin'
themesDir = './themes'

enableEmoji=true

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "homepage"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive"
    weight = 2

  [[menu.main]]
    identifier = "profile"
    name = "Profile"
    url = "/profile"
    weight = 3
